**Products Name & It's Attribute**

In [1]:
record = {"101": {"Name": "Apple  Juice",  "Price": 50, "Quantity": 1,  "Discount" : 5,  "Category" : 'A'},
          "102": {"Name": "Mango  Juice",  "Price": 60, "Quantity": 2, "Discount" : 10,  "Category" : 'B'},
          "103": {"Name": "Orange  Juice", "Price": 70, "Quantity": 3,  "Discount" : 15, "Category" : 'C'},
          "104": {"Name": "Pineapple Juice", "Price": 80, "Quantity": 4, "Discount" : 10, "Category": 'A'},
          "105": {"Name": "Milk  Shake",  "Price": 90,  "Quantity": 5,  "Discount" : 5,  "Category" : 'A'},
          "106": {"Name": "Badam Shake", "Price": 100,  "Quantity": 6, "Discount" : 10, "Category" :  'B'},
          "107": {"Name": "Chicken Chilli", "Price": 110, "Quantity": 7, "Discount" : 10, "Category": 'A'},
          "108": {"Name": "Chockolate Cake", "Price": 120,"Quantity": 8, "Discount" : 15, "Category": 'A'},
          "109": {"Name": "Ice-cream",  "Price": 130,  "Quantity": 9,  "Discount" : 20,  "Category" : 'D'},
          "110": {"Name": "Sandwitch",  "Price": 140,  "Quantity": 9,  "Discount"  : 10, "Category" : 'A'},
          "111": {"Name": "Beet Juice ",  "Price": 150, "Quantity": 7,  "Discount" : 10, "Category" : 'B'},
          "112": {"Name": "Carrot Juice",  "Price": 160, "Quantity": 10, "Discount" : 15, "Category": 'C'},
          "113": {"Name": "Grape Juice",  "Price": 170, "Quantity": 11, "Discount" : 25, "Category" : 'A'},
          "114": {"Name": "Tomato Juice", "Price": 180, "Quantity": 12, "Discount" : 30, "Category" : 'D'},
          "115": {"Name": "Water Bottle",  "Price": 190, "Quantity": 15, "Discount" : 5, "Category" : 'A'},
          "116": {"Name": "Dairy Milk",  "Price": 200,  "Quantity": 17, "Discount" : 10, "Category" : 'B'},
          "117": {"Name": "Fifty-Fifty",  "Price": 210, "Quantity": 20, "Discount" : 15, "Category" : 'A'},
          "118": {"Name": "Marie Gold",  "Price": 220, "Quantity": 21,  "Discount" : 20, "Category" : 'C'},
          "119": {"Name": "Lolly-pop",  "Price": 230,  "Quantity": 22,  "Discount" : 25, "Category" : 'C'},
          "120": {"Name": "Good Day",  "Price": 240,  "Quantity": 25,  "Discount" : 20,  "Category" : 'A'},
          "121": {"Name": "Chaska Maska",  "Price": 250,"Quantity": 27, "Discount" : 15, "Category" : 'A'},
          "122": {"Name": "Egg Noddle",  "Price": 260, "Quantity": 28,  "Discount" : 10, "Category" : 'A'},
          "123": {"Name": "Veg  Noddle",  "Price": 270, "Quantity": 30, "Discount" : 5,  "Category" : 'B'},
          "124": {"Name": "Watermelon",  "Price": 280,  "Quantity": 34, "Discount" : 10, "Category" : 'C'},
          "125": {"Name": "Stroberry",  "Price": 290,  "Quantity": 35,  "Discount" : 15, "Category" : 'A'},
          "126": {"Name": "Lemon Juice", "Price": 300, "Quantity": 37,  "Discount" : 20, "Category" : 'D'},
          "127": {"Name": "Pomegranate", "Price": 400, "Quantity": 40, "Discount" : 25,  "Category" : 'A'},
          "128": {"Name": "Egg  Pop",   "Price": 30,  "Quantity": 12,  "Discount" : 5,   "Category" : 'A'},
          "129": {"Name": "Vege  Pop",  "Price": 20,  "Quantity": 14,  "Discount" : 5,   "Category" : 'A'},
          "130": {"Name": "Sweet Lime", "Price": 100, "Quantity": 100, "Discount" : 15, "Category" : 'A'},}

In [2]:
record

{'101': {'Category': 'A',
  'Discount': 5,
  'Name': 'Apple  Juice',
  'Price': 50,
  'Quantity': 1},
 '102': {'Category': 'B',
  'Discount': 10,
  'Name': 'Mango  Juice',
  'Price': 60,
  'Quantity': 2},
 '103': {'Category': 'C',
  'Discount': 15,
  'Name': 'Orange  Juice',
  'Price': 70,
  'Quantity': 3},
 '104': {'Category': 'A',
  'Discount': 10,
  'Name': 'Pineapple Juice',
  'Price': 80,
  'Quantity': 4},
 '105': {'Category': 'A',
  'Discount': 5,
  'Name': 'Milk  Shake',
  'Price': 90,
  'Quantity': 5},
 '106': {'Category': 'B',
  'Discount': 10,
  'Name': 'Badam Shake',
  'Price': 100,
  'Quantity': 6},
 '107': {'Category': 'A',
  'Discount': 10,
  'Name': 'Chicken Chilli',
  'Price': 110,
  'Quantity': 7},
 '108': {'Category': 'A',
  'Discount': 15,
  'Name': 'Chockolate Cake',
  'Price': 120,
  'Quantity': 8},
 '109': {'Category': 'D',
  'Discount': 20,
  'Name': 'Ice-cream',
  'Price': 130,
  'Quantity': 9},
 '110': {'Category': 'A',
  'Discount': 10,
  'Name': 'Sandwitch',
  'Price': 140,
  'Quantity': 9},
 '111': {'Category': 'B',
  'Discount': 10,
  'Name': 'Beet Juice ',
  'Price': 150,
  'Quantity': 7},
 '112': {'Category': 'C',
  'Discount': 15,
  'Name': 'Carrot Juice',
  'Price': 160,
  'Quantity': 10},
 '113': {'Category': 'A',
  'Discount': 25,
  'Name': 'Grape Juice',
  'Price': 170,
  'Quantity': 11},
 '114': {'Category': 'D',
  'Discount': 30,
  'Name': 'Tomato Juice',
  'Price': 180,
  'Quantity': 12},
 '115': {'Category': 'A',
  'Discount': 5,
  'Name': 'Water Bottle',
  'Price': 190,
  'Quantity': 15},
 '116': {'Category': 'B',
  'Discount': 10,
  'Name': 'Dairy Milk',
  'Price': 200,
  'Quantity': 17},
 '117': {'Category': 'A',
  'Discount': 15,
  'Name': 'Fifty-Fifty',
  'Price': 210,
  'Quantity': 20},
 '118': {'Category': 'C',
  'Discount': 20,
  'Name': 'Marie Gold',
  'Price': 220,
  'Quantity': 21},
 '119': {'Category': 'C',
  'Discount': 25,
  'Name': 'Lolly-pop',
  'Price': 230,
  'Quantity': 22},
 '120': {'Category': 'A',
  'Discount': 20,
  'Name': 'Good Day',
  'Price': 240,
  'Quantity': 25},
 '121': {'Category': 'A',
  'Discount': 15,
  'Name': 'Chaska Maska',
  'Price': 250,
  'Quantity': 27},
 '122': {'Category': 'A',
  'Discount': 10,
  'Name': 'Egg Noddle',
  'Price': 260,
  'Quantity': 28},
 '123': {'Category': 'B',
  'Discount': 5,
  'Name': 'Veg  Noddle',
  'Price': 270,
  'Quantity': 30},
 '124': {'Category': 'C',
  'Discount': 10,
  'Name': 'Watermelon',
  'Price': 280,
  'Quantity': 34},
 '125': {'Category': 'A',
  'Discount': 15,
  'Name': 'Stroberry',
  'Price': 290,
  'Quantity': 35},
 '126': {'Category': 'D',
  'Discount': 20,
  'Name': 'Lemon Juice',
  'Price': 300,
  'Quantity': 37},
 '127': {'Category': 'A',
  'Discount': 25,
  'Name': 'Pomegranate',
  'Price': 400,
  'Quantity': 40},
 '128': {'Category': 'A',
  'Discount': 5,
  'Name': 'Egg  Pop',
  'Price': 30,
  'Quantity': 12},
 '129': {'Category': 'A',
  'Discount': 5,
  'Name': 'Vege  Pop',
  'Price': 20,
  'Quantity': 14},
 '130': {'Category': 'A',
  'Discount': 15,
  'Name': 'Sweet Lime',
  'Price': 100,
  'Quantity': 100}}

In [3]:
record['101']["Name"]

'Apple  Juice'

In [8]:
reg = '101'

print(record[reg]['Name'])
print(record[reg]['Quantity'])
print(record[reg]['Price'])
print(record[reg]['Discount'])
print(record[reg]['Category'])

Apple  Juice
1
50
5
A

In [9]:
import json

In [10]:
js = json.dumps(record)

In [11]:
js

'{"101": {"Name": "Apple  Juice", "Price": 50, "Quantity": 1, "Discount": 5, "Category": "A"}, "102": {"Name": "Mango  Juice", "Price": 60, "Quantity": 2, "Discount": 10, "Category": "B"}, "103": {"Name": "Orange  Juice", "Price": 70, "Quantity": 3, "Discount": 15, "Category": "C"}, "104": {"Name": "Pineapple Juice", "Price": 80, "Quantity": 4, "Discount": 10, "Category": "A"}, "105": {"Name": "Milk  Shake", "Price": 90, "Quantity": 5, "Discount": 5, "Category": "A"}, "106": {"Name": "Badam Shake", "Price": 100, "Quantity": 6, "Discount": 10, "Category": "B"}, "107": {"Name": "Chicken Chilli", "Price": 110, "Quantity": 7, "Discount": 10, "Category": "A"}, "108": {"Name": "Chockolate Cake", "Price": 120, "Quantity": 8, "Discount": 15, "Category": "A"}, "109": {"Name": "Ice-cream", "Price": 130, "Quantity": 9, "Discount": 20, "Category": "D"}, "110": {"Name": "Sandwitch", "Price": 140, "Quantity": 9, "Discount": 10, "Category": "A"}, "111": {"Name": "Beet Juice ", "Price": 150, "Quantity": 7, "Discount": 10, "Category": "B"}, "112": {"Name": "Carrot Juice", "Price": 160, "Quantity": 10, "Discount": 15, "Category": "C"}, "113": {"Name": "Grape Juice", "Price": 170, "Quantity": 11, "Discount": 25, "Category": "A"}, "114": {"Name": "Tomato Juice", "Price": 180, "Quantity": 12, "Discount": 30, "Category": "D"}, "115": {"Name": "Water Bottle", "Price": 190, "Quantity": 15, "Discount": 5, "Category": "A"}, "116": {"Name": "Dairy Milk", "Price": 200, "Quantity": 17, "Discount": 10, "Category": "B"}, "117": {"Name": "Fifty-Fifty", "Price": 210, "Quantity": 20, "Discount": 15, "Category": "A"}, "118": {"Name": "Marie Gold", "Price": 220, "Quantity": 21, "Discount": 20, "Category": "C"}, "119": {"Name": "Lolly-pop", "Price": 230, "Quantity": 22, "Discount": 25, "Category": "C"}, "120": {"Name": "Good Day", "Price": 240, "Quantity": 25, "Discount": 20, "Category": "A"}, "121": {"Name": "Chaska Maska", "Price": 250, "Quantity": 27, "Discount": 15, "Category": "A"}, "122": {"Name": "Egg Noddle", "Price": 260, "Quantity": 28, "Discount": 10, "Category": "A"}, "123": {"Name": "Veg  Noddle", "Price": 270, "Quantity": 30, "Discount": 5, "Category": "B"}, "124": {"Name": "Watermelon", "Price": 280, "Quantity": 34, "Discount": 10, "Category": "C"}, "125": {"Name": "Stroberry", "Price": 290, "Quantity": 35, "Discount": 15, "Category": "A"}, "126": {"Name": "Lemon Juice", "Price": 300, "Quantity": 37, "Discount": 20, "Category": "D"}, "127": {"Name": "Pomegranate", "Price": 400, "Quantity": 40, "Discount": 25, "Category": "A"}, "128": {"Name": "Egg  Pop", "Price": 30, "Quantity": 12, "Discount": 5, "Category": "A"}, "129": {"Name": "Vege  Pop", "Price": 20, "Quantity": 14, "Discount": 5, "Category": "A"}, "130": {"Name": "Sweet Lime", "Price": 100, "Quantity": 100, "Discount": 15, "Category": "A"}}'

In [12]:
fd = open("record.json",'w')

fd.write(js)

fd.close()

**Read Data From JASON**

In [13]:
fd = open("record.json",'r')
r = fd.read()
fd.close()

record = json.loads(r)

In [14]:
record

{'101': {'Category': 'A',
  'Discount': 5,
  'Name': 'Apple  Juice',
  'Price': 50,
  'Quantity': 1},
 '102': {'Category': 'B',
  'Discount': 10,
  'Name': 'Mango  Juice',
  'Price': 60,
  'Quantity': 2},
 '103': {'Category': 'C',
  'Discount': 15,
  'Name': 'Orange  Juice',
  'Price': 70,
  'Quantity': 3},
 '104': {'Category': 'A',
  'Discount': 10,
  'Name': 'Pineapple Juice',
  'Price': 80,
  'Quantity': 4},
 '105': {'Category': 'A',
  'Discount': 5,
  'Name': 'Milk  Shake',
  'Price': 90,
  'Quantity': 5},
 '106': {'Category': 'B',
  'Discount': 10,
  'Name': 'Badam Shake',
  'Price': 100,
  'Quantity': 6},
 '107': {'Category': 'A',
  'Discount': 10,
  'Name': 'Chicken Chilli',
  'Price': 110,
  'Quantity': 7},
 '108': {'Category': 'A',
  'Discount': 15,
  'Name': 'Chockolate Cake',
  'Price': 120,
  'Quantity': 8},
 '109': {'Category': 'D',
  'Discount': 20,
  'Name': 'Ice-cream',
  'Price': 130,
  'Quantity': 9},
 '110': {'Category': 'A',
  'Discount': 10,
  'Name': 'Sandwitch',
  'Price': 140,
  'Quantity': 9},
 '111': {'Category': 'B',
  'Discount': 10,
  'Name': 'Beet Juice ',
  'Price': 150,
  'Quantity': 7},
 '112': {'Category': 'C',
  'Discount': 15,
  'Name': 'Carrot Juice',
  'Price': 160,
  'Quantity': 10},
 '113': {'Category': 'A',
  'Discount': 25,
  'Name': 'Grape Juice',
  'Price': 170,
  'Quantity': 11},
 '114': {'Category': 'D',
  'Discount': 30,
  'Name': 'Tomato Juice',
  'Price': 180,
  'Quantity': 12},
 '115': {'Category': 'A',
  'Discount': 5,
  'Name': 'Water Bottle',
  'Price': 190,
  'Quantity': 15},
 '116': {'Category': 'B',
  'Discount': 10,
  'Name': 'Dairy Milk',
  'Price': 200,
  'Quantity': 17},
 '117': {'Category': 'A',
  'Discount': 15,
  'Name': 'Fifty-Fifty',
  'Price': 210,
  'Quantity': 20},
 '118': {'Category': 'C',
  'Discount': 20,
  'Name': 'Marie Gold',
  'Price': 220,
  'Quantity': 21},
 '119': {'Category': 'C',
  'Discount': 25,
  'Name': 'Lolly-pop',
  'Price': 230,
  'Quantity': 22},
 '120': {'Category': 'A',
  'Discount': 20,
  'Name': 'Good Day',
  'Price': 240,
  'Quantity': 25},
 '121': {'Category': 'A',
  'Discount': 15,
  'Name': 'Chaska Maska',
  'Price': 250,
  'Quantity': 27},
 '122': {'Category': 'A',
  'Discount': 10,
  'Name': 'Egg Noddle',
  'Price': 260,
  'Quantity': 28},
 '123': {'Category': 'B',
  'Discount': 5,
  'Name': 'Veg  Noddle',
  'Price': 270,
  'Quantity': 30},
 '124': {'Category': 'C',
  'Discount': 10,
  'Name': 'Watermelon',
  'Price': 280,
  'Quantity': 34},
 '125': {'Category': 'A',
  'Discount': 15,
  'Name': 'Stroberry',
  'Price': 290,
  'Quantity': 35},
 '126': {'Category': 'D',
  'Discount': 20,
  'Name': 'Lemon Juice',
  'Price': 300,
  'Quantity': 37},
 '127': {'Category': 'A',
  'Discount': 25,
  'Name': 'Pomegranate',
  'Price': 400,
  'Quantity': 40},
 '128': {'Category': 'A',
  'Discount': 5,
  'Name': 'Egg  Pop',
  'Price': 30,
  'Quantity': 12},
 '129': {'Category': 'A',
  'Discount': 5,
  'Name': 'Vege  Pop',
  'Price': 20,
  'Quantity': 14},
 '130': {'Category': 'A',
  'Discount': 15,
  'Name': 'Sweet Lime',
  'Price': 100,
  'Quantity': 100}}

**Add New Item Into Inventory**

In [18]:

prod_id = str(input("Enter product id:"))
name = str(input("Enter Name:"))
price = int(input("Enter Price:"))
quantity = int(input("Enter Quantity:"))
discount = int(input("Enter Discount:"))
category = str(input("Enter Category:"))

record[prod_id] = {'Name': name, 'Price': price, 'Quantity': quantity, 'Discount': discount, 'Category': category}
                   


js = json.dumps(record)

fd = open("record.json",'w')
fd.write(js)
fd.close()

Enter product id:131
Enter Name:Fruity
Enter Price:20
Enter Quantity:3
Enter Discount:5
Enter Category:A

In [19]:
record

{'101': {'Category': 'A',
  'Discount': 5,
  'Name': 'Apple  Juice',
  'Price': 50,
  'Quantity': 1},
 '102': {'Category': 'B',
  'Discount': 10,
  'Name': 'Mango  Juice',
  'Price': 60,
  'Quantity': 2},
 '103': {'Category': 'C',
  'Discount': 15,
  'Name': 'Orange  Juice',
  'Price': 70,
  'Quantity': 3},
 '104': {'Category': 'A',
  'Discount': 10,
  'Name': 'Pineapple Juice',
  'Price': 80,
  'Quantity': 4},
 '105': {'Category': 'A',
  'Discount': 5,
  'Name': 'Milk  Shake',
  'Price': 90,
  'Quantity': 5},
 '106': {'Category': 'B',
  'Discount': 10,
  'Name': 'Badam Shake',
  'Price': 100,
  'Quantity': 6},
 '107': {'Category': 'A',
  'Discount': 10,
  'Name': 'Chicken Chilli',
  'Price': 110,
  'Quantity': 7},
 '108': {'Category': 'A',
  'Discount': 15,
  'Name': 'Chockolate Cake',
  'Price': 120,
  'Quantity': 8},
 '109': {'Category': 'D',
  'Discount': 20,
  'Name': 'Ice-cream',
  'Price': 130,
  'Quantity': 9},
 '110': {'Category': 'A',
  'Discount': 10,
  'Name': 'Sandwitch',
  'Price': 140,
  'Quantity': 9},
 '111': {'Category': 'B',
  'Discount': 10,
  'Name': 'Beet Juice ',
  'Price': 150,
  'Quantity': 7},
 '112': {'Category': 'C',
  'Discount': 15,
  'Name': 'Carrot Juice',
  'Price': 160,
  'Quantity': 10},
 '113': {'Category': 'A',
  'Discount': 25,
  'Name': 'Grape Juice',
  'Price': 170,
  'Quantity': 11},
 '114': {'Category': 'D',
  'Discount': 30,
  'Name': 'Tomato Juice',
  'Price': 180,
  'Quantity': 12},
 '115': {'Category': 'A',
  'Discount': 5,
  'Name': 'Water Bottle',
  'Price': 190,
  'Quantity': 15},
 '116': {'Category': 'B',
  'Discount': 10,
  'Name': 'Dairy Milk',
  'Price': 200,
  'Quantity': 17},
 '117': {'Category': 'A',
  'Discount': 15,
  'Name': 'Fifty-Fifty',
  'Price': 210,
  'Quantity': 20},
 '118': {'Category': 'C',
  'Discount': 20,
  'Name': 'Marie Gold',
  'Price': 220,
  'Quantity': 21},
 '119': {'Category': 'C',
  'Discount': 25,
  'Name': 'Lolly-pop',
  'Price': 230,
  'Quantity': 22},
 '120': {'Category': 'A',
  'Discount': 20,
  'Name': 'Good Day',
  'Price': 240,
  'Quantity': 25},
 '121': {'Category': 'A',
  'Discount': 15,
  'Name': 'Chaska Maska',
  'Price': 250,
  'Quantity': 27},
 '122': {'Category': 'A',
  'Discount': 10,
  'Name': 'Egg Noddle',
  'Price': 260,
  'Quantity': 28},
 '123': {'Category': 'B',
  'Discount': 5,
  'Name': 'Veg  Noddle',
  'Price': 270,
  'Quantity': 30},
 '124': {'Category': 'C',
  'Discount': 10,
  'Name': 'Watermelon',
  'Price': 280,
  'Quantity': 34},
 '125': {'Category': 'A',
  'Discount': 15,
  'Name': 'Stroberry',
  'Price': 290,
  'Quantity': 35},
 '126': {'Category': 'D',
  'Discount': 20,
  'Name': 'Lemon Juice',
  'Price': 300,
  'Quantity': 37},
 '127': {'Category': 'A',
  'Discount': 25,
  'Name': 'Pomegranate',
  'Price': 400,
  'Quantity': 40},
 '128': {'Category': 'A',
  'Discount': 5,
  'Name': 'Egg  Pop',
  'Price': 30,
  'Quantity': 12},
 '129': {'Category': 'A',
  'Discount': 5,
  'Name': 'Vege  Pop',
  'Price': 20,
  'Quantity': 14},
 '130': {'Category': 'A',
  'Discount': 15,
  'Name': 'Sweet Lime',
  'Price': 100,
  'Quantity': 100},
 '131': {'Category': 'A',
  'Discount': 5,
  'Name': 'Fruity',
  'Price': 20,
  'Quantity': 3},
 '135': {'Category': 'A',
  'Discount': 12,
  'Name': 'Coca Cola',
  'Price': 50,
  'Quantity': 5}}

In [20]:

del record['131']

In [50]:
record

{'101': {'Category': 'A',
  'Discount': 5,
  'Name': 'Apple Juice',
  'Price': 50,
  'Quantity': 1},
 '102': {'Category': 'B',
  'Discount': 10,
  'Name': 'Mango Juice',
  'Price': 60,
  'Quantity': 2},
 '103': {'Category': 'C',
  'Discount': 15,
  'Name': 'Orange Juice',
  'Price': 70,
  'Quantity': 3},
 '104': {'Category': 'A',
  'Discount': 10,
  'Name': 'Pineapple Juice',
  'Price': 80,
  'Quantity': 4},
 '105': {'Category': 'A',
  'Discount': 5,
  'Name': 'Milk Shake',
  'Price': 90,
  'Quantity': 5},
 '106': {'Category': 'B',
  'Discount': 10,
  'Name': 'Badam Shake',
  'Price': 100,
  'Quantity': 6},
 '107': {'Category': 'A',
  'Discount': 10,
  'Name': 'Banana',
  'Price': 110,
  'Quantity': 7},
 '108': {'Category': 'A',
  'Discount': 15,
  'Name': 'Chocklate',
  'Price': 120,
  'Quantity': 8},
 '109': {'Category': 'D',
  'Discount': 20,
  'Name': 'Ice-cream',
  'Price': 130,
  'Quantity': 9},
 '110': {'Category': 'A',
  'Discount': 10,
  'Name': 'Cake',
  'Price': 140,
  'Quantity': 9},
 '111': {'Category': 'B',
  'Discount': 10,
  'Name': 'Grapes ',
  'Price': 150,
  'Quantity': 7},
 '112': {'Category': 'C',
  'Discount': 15,
  'Name': 'Guava',
  'Price': 160,
  'Quantity': 10},
 '113': {'Category': 'A',
  'Discount': 25,
  'Name': 'Papaya',
  'Price': 170,
  'Quantity': 11},
 '114': {'Category': 'D',
  'Discount': 30,
  'Name': 'Curd',
  'Price': 180,
  'Quantity': 12},
 '115': {'Category': 'A',
  'Discount': 5,
  'Name': 'Water',
  'Price': 190,
  'Quantity': 15},
 '116': {'Category': 'B',
  'Discount': 10,
  'Name': 'Dairy Milk',
  'Price': 200,
  'Quantity': 17},
 '117': {'Category': 'A',
  'Discount': 15,
  'Name': 'Fifty-Fifty',
  'Price': 210,
  'Quantity': 20},
 '118': {'Category': 'C',
  'Discount': 20,
  'Name': 'Marie Gold',
  'Price': 220,
  'Quantity': 21},
 '119': {'Category': 'C',
  'Discount': 25,
  'Name': 'Lolypop',
  'Price': 230,
  'Quantity': 22},
 '120': {'Category': 'A',
  'Discount': 20,
  'Name': 'Good Day',
  'Price': 240,
  'Quantity': 25},
 '121': {'Category': 'A',
  'Discount': 15,
  'Name': 'Chaska Maska',
  'Price': 250,
  'Quantity': 27},
 '122': {'Category': 'A',
  'Discount': 10,
  'Name': 'Lace',
  'Price': 260,
  'Quant': 28},
 '123': {'Category': 'B',
  'Discount': 5,
  'Name': 'Plumb',
  'Price': 270,
  'Quantity': 30},
 '124': {'Category': 'C',
  'Discount': 10,
  'Name': 'Watermelon',
  'Price': 280,
  'Quantity': 34},
 '125': {'Category': 'A',
  'Discount': 15,
  'Name': 'Stroberry',
  'Price': 290,
  'Quantity': 35},
 '126': {'Category': 'D',
  'Discount': 20,
  'Name': 'Lemon Juice',
  'Price': 300,
  'Quantity': 37},
 '127': {'Category': 'A',
  'Discount': 25,
  'Name': 'Pomegranate',
  'Price': 400,
  'Quantity': 40},
 '128': {'Category': 'A',
  'Discount': 5,
  'Name': 'Egg Pop',
  'Price': 30,
  'Quantity': 12},
 '129': {'Category': 'A',
  'Discount': 5,
  'Name': 'Vege Pop',
  'Price': 20,
  'Quantity': 14},
 '130': {'Category': 'A',
  'Discount': 15,
  'Name': 'Sweet Lime',
  'Price': 100,
  'Quantity': 100}}